WebApplication1/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using System.Web.WebPages.Html;

namespace WebApplication1.Models
{
    public class Event
    {
        [ScaffoldColumn(false)]
        [Key]
        public int EventID { get; set; }

        [Display(Name = "Nazwa wydarzenia")]
        [Required(ErrorMessage = "Musisz wprowadzić nazwę")]
        [StringLength(30)]
        public string Name { get; set; }

        [Display(Name = "Miasto")]
        [Required(ErrorMessage = "Musisz podać miasto")]
        [StringLength(30)]
        public string City { get; set; }

        [Display(Name = "Ilość biletów")]
        [Required(ErrorMessage = "Musisz podać ilość")]
        public int NumberOfTickets { get; set; }

        [Display(Name = "Data wydarzenia")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Required(ErrorMessage = "Musisz podać date")]
        public DateTime? TimeDate { get; set; }

        [Display(Name = "Odpłatność")]
        [Required(ErrorMessage = "Wprowadź informację")]
        public string Payment { get; set; }

        [Display(Name = "Cena biletu")]
        [Required(ErrorMessage = "Podaj cene")]
        public int? Price { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "Musisz wprowadzić email kontakowy")]
        public string Email { get; set; }

        [Phone]
        [RegularExpression(@"([\+]){0,1}([0-9]{2})?[\-\s]?[-]?([0-9]{3})\-?[-\s]?([0-9]{3})[-\s]\-?([0-9]{3})$",
                            ErrorMessage = "Numer musi być zapisany w formacie 123-123-123")]
        [Display(Name = "Numer kontaktowy")]
        public string Number { get; set; }

        public string Organizer { get; set; }
        public virtual ICollection<ApplicationUser> AplicationUsers { get; set; }

        public override bool Equals(object obj)
        {
            Event first = obj as Event;
            if (first == null)
                return false;
            else
                return Name.Equals(first.Name) && City.Equals(first.City) && TimeDate.Equals(first.TimeDate) && Payment.Equals(first.Payment);
        }

        public override int GetHashCode()
        {
            return this.Name.GetHashCode() ^ this.City.GetHashCode() ^ this.TimeDate.GetHashCode() ^ this.Payment.GetHashCode();
        }
    }

    public class Search
    {
        [Display(Name = "Data wydarzenia")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Required(ErrorMessage = "Musisz podać date")]
        public DateTime? TimeDate { get; set; }

        [Display(Name = "Miasto")]
        [Required(ErrorMessage = "Musisz podać miasto")]
        [StringLength(30)]
        public string City { get; set; }
    }
}

WebApplication1/Controllers/EventController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.Net.Mail;

namespace WebApplication1.Controllers
{

    public class EventController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Event
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            return View(db.Events.ToList());
        }
        [Authorize]
        public ActionResult CreateEvent()
        {
            Event FirstEvent = new Event();
            return View(FirstEvent);
        }
        [Authorize]
        [HttpPost]
        public ActionResult CreateEvent(Event FirstEvent)
        {
            if (!ModelState.IsValid)
            {
                return View(FirstEvent);
            }
            else
            {
                foreach (var item in db.Events)
                {
                    if (FirstEvent.Equals(item))
                    {
                        ViewBag.Message = "Istnieje takie wydarzenie!";
                        return View();
                    }
                }
                FirstEvent.Organizer = User.Identity.GetUserId();
                ViewBag.Message = "Stworzono wydarzenie " + FirstEvent.Name;
                db.Events.Add(FirstEvent);
                db.SaveChanges();
                return View();
            }
        }
        public ActionResult Edit(int? id)
        {            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event EditEvent = db.Events.Find(id);
            if (EditEvent.Organizer != User.Identity.GetUserId())
            {
                return View("Error");
            }
            if (EditEvent == null)
            {
                return HttpNotFound();
            }
            return View(EditEvent);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventID,Organizer,Name,City,NumberOfTickets,TimeDate,Payment,Price,Email,Number")] Event EditEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(EditEvent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ImOrganizer");
            }
            return View(EditEvent);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event DeleteEvent = db.Events.Find(id);
            if (DeleteEvent.Organizer != User.Identity.GetUserId())
            {
                return View("Error");
            }
            if (DeleteEvent == null)
            {
                return HttpNotFound();
            }
            return View(DeleteEvent);
        }

        // POST: strudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event DeleteEvent = db.Events.Find(id);
            db.Events.Remove(DeleteEvent);
            db.SaveChanges();
            return RedirectToAction("ImOrganizer");
        }
        [Authorize]
        public ActionResult ImOrganizer()
        {
            string userID = User.Identity.GetUserId();
            var MyEvents = new List<Event>();
            foreach (var item in db.Events)
            {
                if(item.Organizer == userID)
                   MyEvents.Add(db.Events.Find(item.EventID));
            }
            return View(MyEvents);
        }
        [Authorize]
        public ActionResult SignUp(int id)
        {
            string userID = User.Identity.GetUserId();
            EventApplicationUser first = new EventApplicationUser
            {
                IDEvent = id,
                IDUser = userID
            };
            foreach(var item in db.EventApplicationUsers)
            {
                if (first.Equals(item))
                {
                    ViewBag.Message = "Jestes zapisany na to wydarzenie!";
                    return View("Success");
                }
            }
            Event ReducingTickets = db.Events.Find(id);

                if (ReducingTickets.NumberOfTickets > 0)
                {
                    db.EventApplicationUsers.Add(first);
                    ReducingTickets.NumberOfTickets -= 1;
                    db.SaveChanges();
                }
                return View("Success");
        }
        [Authorize]
        public ActionResult SignOff(int id)
        {
            string userID = User.Identity.GetUserId();
            int key = 0;
            Event IncreaseTickets = db.Events.Find(id);
            foreach(var item in db.EventApplicationUsers)
            {
                if (item.IDEvent == id && item.IDUser == userID)
                {
                    key = item.ID;
                    break;
                }
            }
            EventApplicationUser removeUser = db.EventApplicationUsers.Find(key);
            db.EventApplicationUsers.Remove(removeUser);
            IncreaseTickets.NumberOfTickets += 1;
            db.SaveChanges();
            return View("Success");
        }
        [Authorize]
        public ActionResult MyEvents()
        {
            int[] tab = new int[db.EventApplicationUsers.Count()];
            int i = 0;
            string userID = User.Identity.GetUserId();
            var myEvents = new List<Event>();
            foreach(var item in db.EventApplicationUsers)
            {
                if (item.IDUser == userID)
                {
                    tab[i] = item.IDEvent;
                    i++;
                }
            }
            for(int j=0; j<i; j++)
            {
                myEvents.Add(db.Events.Find(tab[j]));
            }
            return View(myEvents);
        }
        public ActionResult Search()
        {
            Search SearchEvents = new Search();
            return View(SearchEvents);
        }
        [HttpPost]
        public ActionResult Search(Search SearchEvents)
        {
            var events = new List<Event>();
            if (!ModelState.IsValid)
            {
                return View(SearchEvents);
            }
            else
            {
                foreach(var item in db.Events)
                {
                    if(item.City == SearchEvents.City && item.TimeDate == SearchEvents.TimeDate)
                    {
                        events.Add(item);
                    }
                }
                if (events.Count() == 0)
                {
                    ViewBag.Message = "Nie znaleziono żadnego wydarzenia ";
                    return View();
                }
                else
                    return View("List", events);
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event FirstEvent = db.Events.Find(id);
            if (FirstEvent == null)
            {
                return HttpNotFound();
            }
            return View(FirstEvent);

        }
        public FileResult CreatePdf(int? id)
        {
            MemoryStream workStream = new MemoryStream();
            StringBuilder status = new StringBuilder("");
            DateTime dTime = DateTime.Now;
            //file name to be created   
            Event FirstEvent = db.Events.Find(id);
            string strPDFFileName = string.Format(FirstEvent.Name + dTime.ToString("yyyyMMdd") + "_mgjmas" + ".pdf");
            Document doc = new Document(PageSize.A5, 50, 50, 25, 25);
            doc.SetMargins(10f, 10f, 10f, 10f);
            BaseFont bfTimes = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1250, false);
            Font times = new Font(bfTimes, 12);
            Font times2 = new Font(bfTimes, 16);
            string Email = "Email: " + FirstEvent.Email;
            string EventName = "Nazwa wydarzenia: " + FirstEvent.Name;
            string City = "Miasto: " + FirstEvent.City;
            string EventDate = "Data wydarzenia: " + FirstEvent.TimeDate.Value.ToString("dd/MM/yyyy");
            string FreePaid = "Odpłatność: " + FirstEvent.Payment;
            string Price = "Cena biletu: " + FirstEvent.Price + "zł";
            Paragraph paraEmail = new Paragraph(Email, times2);
            Paragraph paraEventName = new Paragraph(EventName, times2);
            Paragraph paraCity = new Paragraph(City, times2);
            Paragraph paraEventDate = new Paragraph(EventDate, times2);
            Paragraph paraFreePaid = new Paragraph(FreePaid, times2);
            Paragraph paraPrice = new Paragraph(Price, times2);
            //Create PDF Table with 5 columns  
            PdfPTable tableLayout = new PdfPTable(6);
            doc.SetMargins(20f, 20f, 20f, 20f);
            //Create PDF Table  

            //file will created in this path  
            string strAttachment = Server.MapPath("~/Downloadss/" + strPDFFileName);


            PdfWriter.GetInstance(doc, workStream).CloseStream = false;
            doc.Open();
            Paragraph title = new Paragraph("BILET", new Font(Font.FontFamily.HELVETICA, 20, 1, new iTextSharp.text.BaseColor(0, 0, 0)));
            title.Alignment = Element.ALIGN_MIDDLE;
            doc.Add(title);
            doc.Add(paraEmail);
            doc.Add(paraEventName);
            doc.Add(paraCity);
            doc.Add(paraEventDate);
            doc.Add(paraFreePaid);
            doc.Add(paraPrice);

WebApplication1/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class EventsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: api/Events
        public IQueryable<Event> GetEvents()
        {
            return db.Events;
        }

        // GET: api/Events/5
        [ResponseType(typeof(Event))]
        public IHttpActionResult GetEvent(int id)
        {
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return NotFound();
            }

            return Ok(@event);
        }

        // PUT: api/Events/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutEvent(int id, Event @event)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != @event.EventID)
            {
                return BadRequest();
            }

            db.Entry(@event).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EventExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Events
        [ResponseType(typeof(Event))]
        public IHttpActionResult PostEvent(Event @event)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Events.Add(@event);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = @event.EventID }, @event);
        }

        // DELETE: api/Events/5
        [ResponseType(typeof(Event))]
        public IHttpActionResult DeleteEvent(int id)
        {
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return NotFound();
            }

            db.Events.Remove(@event);
            db.SaveChanges();

            return Ok(@event);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool EventExists(int id)
        {
            return db.Events.Count(e => e.EventID == id) > 0;
        }
    }
}

WebApplication1/Views/Event/CreateEvent.cshtml
@model WebApplication1.Models.Event
@{
    ViewBag.Title = "Stwórz wydarzenie";
}
<h2 class="display-name">Stwórz wydarzenie</h2>
<span style="font-size: 15px; color: green;">
    <h3>@ViewBag.Message</h3>
</span>
<link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
    $(function () {
            $(".Event").datepicker({
                dateFormat: "dd/MM/yy"
            })
        });</script>
    <script type="text/javascript">
    $(document).ready(function () {
            $("#cena").hide();
            $('input[name=Payment]').click(function () {
                if ($('input[name=Payment]:checked').val() === "płatne") {
                    $('#cena').show();
                } else {
                    $('#cena').hide();
                }
            });
        });</script>
}
<style type="text/css">

    .display-name {
        color: white;
    }

    .textboxcontent {
        color: black;
    }

    .calendarcontent {
        color: black;
    }
</style>
<!DOCTYPE html>
<body>
    <div id="createevent">
        <font size="3">
            @using (Html.BeginForm("CreateEvent", "Event", new { @style = "color: #ffffff;" }))
            {
                <span class="display-name">@Html.DisplayNameFor(model => Model.Name)</span>
                <div>
                    <span class="textboxcontent">@Html.TextBoxFor(model => Model.Name, new { htmlAttributes = new { @class = "form-control" }, @style = "color: #000000" })</span>
                    @Html.ValidationMessageFor(model => Model.Name, "", new { @class = "text-danger" })
                </div>
                <span class="display-name">@Html.DisplayNameFor(model => Model.City)</span>
                <div>
                    <span class="textboxcontent">@Html.TextBoxFor(model => Model.City, new { @style = "color: #000000" })</span>
                    @Html.ValidationMessageFor(model => Model.City, "", new { @class = "text-danger" })
                </div>
                <span class="display-name">@Html.DisplayNameFor(model => Model.NumberOfTickets)</span>
                <div>
                    @Html.EditorFor(model => Model.NumberOfTickets, new { htmlAttributes = new { @style = "color: #000000" } })
                    @Html.ValidationMessageFor(model => Model.NumberOfTickets, "", new { @class = "text-danger" })
                </div>
                <span class="display-name">@Html.DisplayNameFor(model => Model.TimeDate)</span>
                <div>
                    <span class="calendarcontent">@Html.EditorFor(model => Model.TimeDate, new { htmlAttributes = new { @class = "Event" }, @style = "color: #000000;" })</span>
                    @Html.ValidationMessageFor(model => Model.TimeDate, "", new { @class = "text-danger" })
                </div>
                <span class="display-name">@Html.DisplayNameFor(model => Model.Payment)</span>
                <div>
                    <span class="display-name">Darmowe @Html.RadioButtonFor(model => Model.Payment, "darmowe")</span>
                    <span class="display-name">Platne @Html.RadioButtonFor(model => Model.Payment, "płatne")</span>
                </div>
                <div id="cena">
                    <span class="display-name">@Html.DisplayNameFor(model => Model.Price) <br /></span>
                    <span class="textboxcontent">@Html.TextBoxFor(model => Model.Price, new { @Value = "0" })</span>
                </div>

                <span class="display-name">@Html.DisplayNameFor(model => Model.Email)</span>
                <div>
                    <span class="textboxcontent">@Html.TextBoxFor(model => Model.Email)</span>
                    @Html.ValidationMessageFor(model => Model.Email, "", new { @class = "text-danger" })
                </div>
                <span class="display-name">@Html.DisplayNameFor(model => Model.Number)</span>
                <div>
                    <span class="textboxcontent">@Html.TextBoxFor(model => Model.Number)</span>
                    @Html.ValidationMessageFor(model => Model.Number, "", new { @class = "text-danger" })
                </div>


                <input id="Submit1" type="submit" value="Utwórz" style="color: black;" />

            }
        </font>
    </div>
</body>

WebApplication1/Views/Event/Delete.cshtml
@model WebApplication1.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Jesteś pewny, że chcesz usunąć to wydarzenie?</h3>
<div>
    <hr />

    <p align="center">
        <h5>
            <dl class="dl-horizontal">

                <dt>

                    @Html.DisplayNameFor(Model => Model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(Model => Model.Name)
                </dd>
            </dl>
        </h5>
    </p>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <p align="left">
                <input type="submit" value="Usun" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "ImOrganizer")
            </p>
        </div>
    }
</div>

WebApplication1/Views/Event/Details.cshtml
@model WebApplication1.Models.Event
@{
    ViewBag.Title = "Szczegóły";
}
<div>
    <h4>Wydarzenie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "List", "Event")
</p>

WebApplication1/Views/Event/Form.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Form</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

WebApplication1/Views/Event/ImOrganizer.cshtml
@model IEnumerable<WebApplication1.Models.Event>
@{
    ViewBag.Title = "Zarządzanie wydarzeniami";
}
<h4>@ViewBag.Title</h4>

@*<h4>
    @Html.ActionLink("Stworz wydarzenie", "CreateEvent", "Event")<br />
    @Html.ActionLink("Strona główna", "Index", "Manage")<br />
</h4>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name) <br />
                @Html.ActionLink("Edytuj", "Edit", new { id = item.EventID }) <br />
                @Html.ActionLink("Usun", "Delete", new { id = item.EventID }) <br />
                @Html.ActionLink("Wyslij maile", "Sendemails", new { id = item.EventID }) <br />
            </td>
        </tr>
    }
</table>

WebApplication1/Views/Event/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

WebApplication1/Views/Event/List.cshtml
@model IEnumerable<WebApplication1.Models.Event>
@{
    ViewBag.Title = "Lista Wydarzeń";
}
<h4>@ViewBag.Message</h4>
<style type="text/css">
    .bezramki{
        border-top: 0;
    }
</style>
<h2>Lista Wydarzeń</h2>
<table class="table">
    <tr class="bezramki">
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeDate)
        </th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model)

    {
    <tr>
        <td width="25%">
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td width="25%">
            @Html.DisplayFor(modelItem => item.City)
        </td>

        <td width="25%">
            @Html.DisplayFor(modelItem => item.TimeDate)
        </td>
        <td width="25%">
            @Html.ActionLink("Szczegóły", "Details", new { id = item.EventID })
        </td>
        <td width="30%">
            @Html.ActionLink("Zapisz się", "SignUp", new { id = item.EventID })
        </td>
    </tr>
    }
</table>

WebApplication1/Views/Event/MyEvents.cshtml
@model IEnumerable<WebApplication1.Models.Event>
@{
    ViewBag.Title = "Moje wydarzenia";
}
@*<h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>*@
<h2>Moje wydarzenia</h2>
@*@Html.ActionLink("Stworz wydarzenie", "CreateEvent", "Event")<br />
@Html.ActionLink("Strona główna", "Index", "Manage")<br />*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>

        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name) <br />
                @Html.ActionLink("Szczegoly", "Details", new { id = item.EventID }) <br />
                @Html.ActionLink("Pobierz bilet", "CreatePDF", new { id = item.EventID })<br />
                @Html.ActionLink("Wypisz sie", "SignOff", new { id = item.EventID })<br />
            </td>
        </tr>
    }
</table>

WebApplication1/Views/Event/Search.cshtml
@model WebApplication1.Models.Search
@{
    ViewBag.Title = "Wyszukiwarka";
}
<span style="font-size: 15px; color: green;">
    <h3>@ViewBag.Message</h3>
</span>
<link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script>
        $(function () {
            $(".Event").datepicker({
                dateFormat: "dd/MM/yy"
            })
        });</script>
}
<style type="text/css">

    .display-name {
        color: white;
    }

    .textboxcontent {
        color: black;
    }

    .calendarcontent {
        color: black;
    }
    #guzik{
        padding-top: 15px;
    }
</style>
<!DOCTYPE html>
<body>
    <div id="search">
        <font size="3">
            @using (Html.BeginForm("Search", "Event", new { @style = "color: #ffffff;" }))
            {
            <span class="display-name">@Html.DisplayNameFor(model => Model.TimeDate)</span>
            <div>
                <span class="calendarcontent">@Html.EditorFor(model => Model.TimeDate, new { htmlAttributes = new { @class = "Event" }, @style = "color: #000000;" })</span>
                @Html.ValidationMessageFor(model => Model.TimeDate, "", new { @class = "text-danger" })
            </div>
            <span class="display-name">@Html.DisplayNameFor(model => Model.City)</span>
            <div>
                <span class="textboxcontent">@Html.TextBoxFor(model => Model.City, new { @style = "color: #000000" })</span>
                @Html.ValidationMessageFor(model => Model.City, "", new { @class = "text-danger" })
            </div>
            <div id="guzik"><input id="Submit2" type="submit" value="Wyszukaj" style="color: black;" /></div>

        }
        </font>
    </div>
</body>

WebApplication1/Views/Event/Sendemails.cshtml
@model WebApplication1.Models.MailViewModel

@{
    ViewBag.Title = "E-mail";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        #wyslij{
            color: black;
        }
        #tekstboks{
            width: 400px;
        }
        td{
            padding-top: 10px;
        }
        textarea{
            max-width: 500px;
        }
    </style>
</head>

<body>
    <div>
        @using (Html.BeginForm("Sendemails", "Event", FormMethod.Post))
        {
            <center>
                <h1></h1>
                <table>
                    <tr>
                        <td>
                            Temat:
                        </td>
                        <td>
                            @Html.TextBoxFor(model => model.Subject, new { @style = "background-color: #eeeeee;color:black;width=inherit; " } )
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Treść:
                        </td>
                        <td id="tekstboks">
                            @Html.TextAreaFor(model => model.Body, new { rows = "15", cols = "800", @style = "background-color: #eeeeee;color:black; " })
                        </td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>
                            <input type="submit" id="wyslij" value="Wyślij"  />
                        </td>
                    </tr>
                </table>
                <span style="color:green">@ViewBag.Message</span>
            </center>
        }
    </div>
</body>
</html>

WebApplication1/Views/Event/SignUp.cshtml
@model IEnumerable<WebApplication1.Models.Event>
@{
    ViewBag.Title = "Zapisz sie";
}
@ViewBag.Message
<h2>Lista Wydarzeń</h2>
@Html.ActionLink("Stworz wydarzenie", "CreateEvent", "Event")<br />
@Html.ActionLink("Strona główna", "Index")<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)

    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name) <br />
                @Html.ActionLink("Szczegoly", "Details", new { id = item.EventID }) <br />
                @Html.ActionLink("Zapisz sie", "SignUp", new { id = item.EventID })<br />
                @Html.ActionLink("Wypisz sie", "Usun", new { id = item.EventID })<br />
            </td>

        </tr>
    }
</table>

WebApplication1/Views/Event/Success.cshtml
@{
    ViewBag.Title = "Sukces!";
}
@ViewBag.Message
    <h2>Sukces!</h2>